# Generated by Django 5.1.2 on 2024-10-26 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widow', 'Widow')], max_length=20)),
                ('employee_user_id', models.CharField(max_length=20)),
                ('date_of_joining', models.DateField()),
                ('email_id', models.EmailField(max_length=50)),
                ('pan_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pro', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qualification', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('year_of_enrolment', models.CharField(max_length=4)),
                ('university', models.CharField(max_length=100)),
                ('collage', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employeeprofile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_number', models.PositiveBigIntegerField()),
                ('emergency_contact', models.PositiveBigIntegerField()),
                ('personal_email', models.EmailField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='employeeprofile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=10)),
                ('house_no', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='employeeprofile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_number', models.BigIntegerField()),
                ('account_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(choices=[('icici', 'ICICI'), ('hdfc', 'HDFC'), ('iob', 'IOB'), ('sbi', 'SBI'), ('idfc', 'IDFC')], max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_address', models.CharField(max_length=100)),
                ('cheque', models.FileField(upload_to='media/cancel_cheque')),
                ('customer_id', models.BigIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='employeeprofile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity_name', models.CharField(choices=[('Voter_ID', 'Voter_ID'), ('Passport', 'Passport'), ('Aadhar_card', 'Aadhar_card'), ('License', 'License')], max_length=100)),
                ('identity_number', models.CharField(max_length=100)),
                ('front_image', models.ImageField(upload_to='media/identity_cards')),
                ('back_image', models.ImageField(upload_to='media/identity_cards')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_name', to='employeeprofile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('insurer', models.CharField(max_length=100, verbose_name='Policy Provider')),
                ('insured', models.CharField(choices=[('self', 'self'), ('dependent', 'dependent ')], max_length=100)),
                ('type_of_insurance', models.CharField(choices=[('individual', 'Individual'), ('Family Floater', 'Family Floater')], max_length=20)),
                ('sum_insured', models.BigIntegerField()),
                ('policy_type', models.CharField(choices=[('health insurance', 'health insurance'), ('life insurance', 'life insurance'), ('general insurance', 'general insurance')], max_length=50)),
                ('policy_number', models.BigIntegerField()),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_till', models.DateField()),
                ('documentation', models.FileField(upload_to='')),
                ('card', models.FileField(upload_to='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='employeeprofile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DependentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter')], max_length=30)),
                ('dependent_name', models.CharField(max_length=100)),
                ('dependent_DOB', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_info', to='employeeprofile.insuranceinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('position_name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('t1', 'T1'), ('t2', 'T2'), ('t3', 'T3'), ('t4', 'T4'), ('m1', 'M1'), ('m2', 'M2'), ('m3', 'M3'), ('m4', 'M4'), ('s1', 'S1'), ('s2', 'S2'), ('l1', 'L1'), ('l2', 'L2')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.position'),
        ),
        migrations.CreateModel(
            name='ProficiencyCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('since', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media/proficiency_certification')),
                ('grade', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiency_certification', to='employeeprofile.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_name', models.CharField(max_length=100)),
                ('member_since', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_name', to='employeeprofile.employeeprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
