# Generated by Django 5.1.2 on 2024-10-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0003_identitydetail_proficiencycertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='employeeprofile.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='employeeprofile.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='employeeprofile.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent', to='employeeprofile.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employeeprofile.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='identitydetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_name', to='employeeprofile.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='insuranceinfo',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='employeeprofile.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='proficiencycertification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiency_certification', to='employeeprofile.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_name', to='employeeprofile.employeeprofile'),
        ),
    ]
