# Generated by Django 5.1.3 on 2024-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='title',
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
